### ISSUE TITLE
Ok Glass Read This [Feature Request]

### ISSUE THREAD

**Issue by drew5494** [sandlerben/third-eye#2]
Hi Im visually impaired and I think this project is amazing!  
I like how it recognizes objects however if I want it to simply read something, instead of recognizing it and sending it to googles services, it could use a word-recognizer and therefore you wouldn't have to wait for the processing time.

**Comment by sandlerben** [comment]
Hey! We are actually working on this feature right now. Thanks for the request.

Ben

**Comment by sandlerben** [comment]
This feature has been added.

**Comment by drew5494** [comment]
Thank you!
